version: "3.8"

services:
  database:
    image: postgres:latest
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - 2345:5432
    volumes:
      - ./scripts/initdb.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg-data:
